// import React from "react";

const easyWords = [
	["ate", "eight"],
	["bread", "bred"],
	["cell", "sell"],
	["chews", "choose"],
	["meet", "meat"],
	["clothes", "close"],
	["coarse", "course"],
	["crews", "cruise"],
	["capital", "capitol"],
	["dew", "due"],
	["die", "dye"],
	["doe", "dough"],
	["allowed", "aloud"],
	["fur", "fir"],
	["flea", "flee"],
	["jean", "gene"]
];
const mediumWords = [
	["air", "heir"],
	["bale", "bail"],
	["die", "dye"],
	["gait", "gate"],
	["cereal", "serial"],
	["berth", "birth"],
	["chord", "cord"],
	["cite", "site"],
	// ["blue", "blew"],
	// ["creak", "creek"],
	["ceiling", "sealing"],
	["census", "senses"],
	["stare", "stair"],
	// ["queue", "cue"],
	// ["ball", "bawl"],
	["dual", "duel"],
	// ["band", "banned"],
	// ["billed", "build"],
	// ["faze", "phase"],
	["fined", "find"],
	["pee", "pea"],
	["mail", "male"],
	["lessen", "lesson"],
	["peak", "peek"],
	["cash", "cache"],
	["role", "roll"]
];
const hardWords = [
	["compliment", "complement"],
	["advice", "advise"],
	["ale", "ail"],
	["aisle", "isle"],
	["allusion", "illusion"],
	// ["affect", "effect"],
	["holy", "wholly"],
	// ["capital", "capitol"],
	["stationary", "stationery"],
	["complement", "compliment"],
	["council", "counsel"],
	["cannon", "canon"],
	// ["halve", "have"],
	["leased", "least"],
	["desert", "dessert"],
	["overdue", "overdo"],
	["patience", "patients"],
	// ["principal", "principle"],
	["vary", "very"],
	["medal", "metal"],
	["lesson", "lessen"],
	["course", "coarse"],
	["presence", "presents"],
	["scent", "cent"],
	["patients", "patience"],
	["braze", "braise"],
	["raze", "raise"]
];

export { easyWords, mediumWords, hardWords };
